name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels: ['bug']
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Reporter
      description: Who is reporting the bug
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What was supposed to happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: severity
    attributes:
      label: How severe is the bug?
      multiple: true
      options:
        - Low
        - Minor
        - Major
        - Critical
  - type: dropdown
    id: priority
    attributes:
      label: Whats the priority for this bug?
      multiple: true
      options:
        - Low
        - Medium
        - High
  - type: input
    id: jam
    attributes:
      label: Jam link
  - type: input
    id: har
    attributes:
      label: Browser's HAR file link
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Please add any extra notes.
