name: Feature Request
description: Request of new feature.
title: '[Feat]: '
projects: ['Netsuite-Applications/33']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
    validations:
      required: true
